### ISSUE TITLE
Document full action outputs in list

### ISSUE THREAD

**Issue by stacksjb** [nicolaiunrein/cargo-get#86]
It would be EXTREMELY helpful if there was a list of outputs and examples. I spent hours trying to get a single metadata output but couldn't get the syntax quite right.

Based on the code, the only one listed is "outputs.metadata"
````
outputs:
  metadata:
    description: "Cargo package metadata"
    value: ${{ steps.cargo-get.outputs.metadata }}
```

(Obviously there are more subfields, but I don't know what they are).

For an example of a repo that does this really well, see https://github.com/softprops/action-gh-release - notice the sections in their readme where they table list all outputs and inputs.
